name: build-alertmanager

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'alertmanager/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t giammarcoboscaro/alertmanager .
        working-directory: ./alertmanager
      - run: docker push giammarcoboscaro/alertmanager
